config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get('/',{to:'posts#index', as: :posts})
  post('/',{to:'posts#create'})
  # get('/posts/new',{to:'posts#new'})
  # get('/posts/:id',{to:'posts#show', as: :post})
  # delete('/posts/:id',{to:'posts#destroy'})
  # get('/posts/:id/edit',{to:'posts#edit', as: :edit_post})
  # patch('/posts/:id',{to:'posts#update'})

  resources :posts do 
    resources :comments, only:[:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :comment, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates :title, presence: true, uniqueness: {case_sensitive: true}
    validates :body, presence: true, length: {minimum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @post = Post.find(params[:post_id])
        @comment = Comment.new(comment_params)
        @comment.post = @post
        if @comment.save
            redirect_to post_path(@post.id)
        else
            @comments = @post.comments.order(created_at: :desc)
            render '/posts/show'
        end
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = Comment.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post.id)
    end
    


    private

    def comment_params
        params.require(:comment).permit(:comment)
    end
    
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only:[:show, :edit, :update, :destroy]

    def index
        @posts = Post.all.order(created_at: :desc)
    end
    
    def show
        # @post = Post.find(params[:id])
        @comment = Comment.new
        @comments = @post.comments.order(created_at: :desc)
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        if @post.save
            redirect_to post_path(@post.id)
        else
            render :new
        end
    end
    

    def edit
        # @post = Post.find(params[:id])
    end
    
    def update
        # @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to post_path(@post.id)
        else
            render :edit
        end
    end

    def destroy
        # @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end
    
    private 

    def post_params 
        params.require(:post).permit(:title, :body)
    end
    
    def find_post   
        @post = Post.find(params[:id])
    end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>BlogOnRails</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

      <%= stylesheet_link_tag 'application' , media: 'all' %>
      <%= stylesheet_link_tag 'main' , media: 'all' %>

        <%= javascript_pack_tag 'application' %>
</head>

<body>
  <nav class="navbar navbar-light bg-light">
    <div class="container-fluid ">
      <a href="/" class="nav-link home-button">Blog On Rails</a>
      <form class="d-flex">
        <a class="nav-link" aria-current="page" href="/">Home</a>
        <a class="nav-link" aria-current="page" href="/posts/new">New Post</a>

      </form>
    </div>
  </nav>

  <%= yield %>
</body>

</html>

app/views/posts/edit.html.erb
<% if @post.errors.any? %> 
<div class="alert alert-danger">
<ul>
    <%= @post.errors.full_messages.each do |message| %> 
        <li><%= message %> </li>
    <% end %> 
</ul>
</div>
<% end %> 

<div class="container">
    <%= form_with(model: @post) do |form| %>
        <div class="mb-3 mt-3">
            <%= form.label :title, "Title" , class:"form-label" %>
            <%= form.text_field :title, class:"form-control" %>
        </div>
        <div class="mb-3 mt-3">
            <%= form.label :body, "Body" , class:"form-label" %>
            <%= form.text_area :body, cols: 50, rows: 5, class:"form-control" %>
        </div>
        <div class="mb-3 mt-3">
            <%= form.submit "Update Post", class:"btn btn-outline-primary" %>
        </div>
        
    <% end %>
</div>

app/views/posts/index.html.erb
<div class="container">
    <div class="row">
        <% @posts.each do |post| %>
            <div class="col-md-6 col-lg-4 mt-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title title-position">
                            <a href='/posts/<%= post.id %>' class="nav-link"><%= post.title %></a>
                        </h5>
                        <p class="card-text body-position">
                            <%= post.body[0..50] %>
                        </p>
                    </div>
                </div>
            </div>
            <% end %>
    </div>
</div>

app/views/posts/new.html.erb
<% if @post.errors.any? %> 
<div class="alert alert-danger">
<ul>
    <%= @post.errors.full_messages.each do |message| %> 
        <li><%= message %> </li>
    <% end %> 
</ul>
</div>
<% end %> 

<div class="container">
    <%= form_with(model: @post) do |form| %>
        <div class="mb-3 mt-3">
            <%= form.label :title, "Title" , class:"form-label" %>
            <%= form.text_field :title, class:"form-control" %>
        </div>
        <div class="mb-3 mt-3">
            <%= form.label :body, "Body" , class:"form-label" %>
            <%= form.text_area :body, cols: 50, rows: 5, class:"form-control" %>
        </div>
        <div class="mb-3 mt-3">
            <%= form.submit "Create Post", class:"btn btn-outline-primary" %>
        </div>
        
    <% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
    <h2 class="mt-3">
        <%= @post.title %>
    </h2>
    <p>
        <%= @post.body %>
    </p>
    <small>
        Posted <%= time_ago_in_words(@post.created_at) %> ago
    </small>

    <div class="mt-2">
        <div>
            <%= link_to "Edit" , edit_post_path(@post.id), class:"btn btn-outline-primary" %>
                <%= link_to "delete" , post_path(@post.id), method: :delete, data: {confirm: "Are you sure?" },
                    class:"btn btn-outline-primary" %>
        </div>
    </div>

    <%= form_with(model: [@post, @comment]) do |form| %>
        <div class="mb-3, mt-3">
            <%= form.label :comment, "Comment" , class:"form-label" %>
            <%= form.text_area :comment, placeholder:"What's on your mind?", class:"form-control" %>
        </div>
        <div class="mt-3">
            <%= form.submit "Submit" , class:"btn btn-outline-primary" %>
        </div>
        <% end %>

            <div class="mt-3">
                <% @comments.each do |comment| %>
                    <p class="mb-0 mt-3">
                        <%= comment.comment %>
                    </p>
                    <small>
                        Commented <%= time_ago_in_words(comment.created_at) %> ago • 
                        <%= link_to "Delete", post_comment_path(@post.id, comment.id), method: :delete, data: {confirm: "Are you sure?"} %> 
                    </small>
                <% end %>
            </div>



</div>